networks:
  web:
    external: true
  default:
    external: false

  frontend:
    build:
      context: .
      dockerfile: frontend/docker/Dockerfile
    ports:
      - 127.0.0.1:8080:8083
    links:
      - backend
    depends_on:
      - backend
    networks:
      - web
      - default