on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: install npm
        run: 'sudo apt update -y && sudo apt install nodejs npm -y'

      - name: install JQ
        run: 'sudo apt update -y && sudo apt install jq -y'

      - name: install AWS CLI
        run: 'sudo apt update -y && sudo apt install awscli -y'

      - name: Install AWS CDK
        run: 'sudo npm install -g aws-cdk'

      - name: Install Requirements
        run: 'yarn install'

      - name: CDK Version
        run: cdk --version

      - name: CDK Synth
        run: cdk synth

      - name: CDK Deploy Infrastructure
        run: cdk deploy checker-fargate --require-approval never

      - name: Get target instance
        id: target-instance
        run: aws ec2 describe-instances --query 'Reservations[*].Instances[*].[PublicIpAddress]' --filters Name=instance-state-name,Values=running Name=tag:aws:cloudformation:stack-name,Values=checker-fargate --output text

      - name: Get ssh key
        id: ssh-key
        run: aws secretsmanager get-secret-value --secret-id ec2-ssh-key/checker-keypair/private --query SecretString --output text > cdk-key.pem && chmod 400 cdk-key.pem
